### ISSUE TITLE
Deleting a user doesn't delete their personal space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#4195]
ocis 2.0.0-beta.5 local

Steps:
- user Katherine uploads file and creates folder to personal space
- admin deletes user Katherine
- admin get all spaces: `curl -vk 'https://localhost:9200/graph/v1.0/drives' -u admin:admin -vk`

Expected: space with "driveAlias": "personal/katherine" doesn't exist
make sure that no data in: `tree -a /.ocis/storage/users/spaces/katherineSpaceId/`

Actual: space with all data still exist.

**Comment by rhafer** [comment]
> This used to work with the accounts service. Therefore regression.

AFAIR we decided (in some refinement) that deleting a user and deleting its files should be separate things? And deleting user should not automatically remove all the user's personal space.

IIRC  @butonic had a pretty strong opinion on that.

But yeah, either way. We need some way to delete a user's personal space.

**Comment by rhafer** [comment]
Result from refinement:
- for now it's ok to delete the personal space of a user, when deleting the user
- we need to introduce a new permission `DeleteAllSpaces` that the user who's deleting another is user needs to have assigned in order to delete the personal space
- The DeleteUser call in the  GraphAPI should check for all required permission prior to deleting a user. (in order to avoid "half-deleted" users)

**Comment by rhafer** [comment]
@ScharfViktor  https://github.com/cs3org/reva/pull/3202 should fix the permission error you having been seeing. There is still another problem left, was currently Deleting a user will only more the personal space to trash and not purge it. 

Will look into that next.

**Comment by ScharfViktor** [comment]
> @ScharfViktor [cs3org/reva#3202](https://github.com/cs3org/reva/pull/3202) should fix the permission error you having been seeing. There is still another problem left, was currently Deleting a user will only more the personal space to trash and not purge it.
> 
> Will look into that next.

Thanks. it will looks like disabling space? `"deleted": {"state": "trashed"},` in the root section
Do we have to achieve complete deletion or is it okay?

**Comment by rhafer** [comment]
> Thanks. it will looks like disabling space? `"deleted": {"state": "trashed"},` in the root section

Yes.

> Do we have to achieve complete deletion or is it okay?

I think we want complete deleting. The fix is in #4528

**Comment by ScharfViktor** [comment]
sorry for the persistence, but for me it still doesn't work. 

log, when I delete user: 
`2022-09-07T16:15:12+02:00 ERR failed to delete storage space error="error: permission denied: user is not allowed to delete spaces 52f998c3-9c58-498b-bfc8-0cd9fc135ad7" pkg=rgrpc service=storage-users status={"code":8,"message":"permission denied","trace":"00000000000000000000000000000000"} storage_space_id={"opaque_id":"1284d238-aa92-42ce-bdc4-0b0000009157$52f998c3-9c58-498b-bfc8-0cd9fc135ad7!52f998c3-9c58-498b-bfc8-0cd9fc135ad7"} traceid=00000000000000000000000000000000
2022-09-07T16:15:12+02:00 ERR failed to delete storage space error="error: permission denied: user is not allowed to delete spaces 52f998c3-9c58-498b-bfc8-0cd9fc135ad7" pkg=rgrpc service=storage-users status={"code":8,"message":"permission denied","trace":"00000000000000000000000000000000"} storage_space_id={"opaque_id":"1284d238-aa92-42ce-bdc4-0b0000009157$52f998c3-9c58-498b-bfc8-0cd9fc135ad7!52f998c3-9c58-498b-bfc8-0cd9fc135ad7"} traceid=00000000000000000000000000000000`

I understand that the admin is trying to delete in two steps personal space of the user but he has not permissions

if we check admins permissions
curl -s -k -u admin:admin -X POST https://localhost:9200/api/v0/settings/roles-list -d '{}' -H 'Content-Type: application/json'

looks like that admin can delete and it should work. Am I missing something? 

`"id":"5de9fe0a-4bc5-4a47-b758-28f370caf169","name":"delete-all-home-spaces","displayName":"Delete All Home Spaces","description":"This permission allows to delete home spaces."`

**Comment by micbar** [comment]
needs a reva update. I am working on it in #4522

**Comment by ScharfViktor** [comment]
Thanks, checked again on update-reva-edge branch. All works fine
